version: '3'

dotenv: ['.env']

tasks:
  build:image:
    prompt: Have you made sure the version number is up to date?
    desc: builds publishable python package
    cmds:
      - poetry build
  test:
    desc: runs tests inside the virtualenv
    summary:
      runs all the tests inside the virtualenv, optionally
      provide the name of the test as an argument to run a single test
    cmds:
      - poetry run coverage run -m pytest -s --tap tests/{{.CLI_ARGS}}
  test:list:
    desc: lists the available tests
    summary:
      runs collect only on pytest to list the tests available
    cmds:
      - poetry run pytest --co
  test:coverreport:
    desc: runs coverage inside the server container
    cmds:
      - poetry run coverage report -m
  dev:textual:
    desc: runs the textual cli
    cmds:
      - poetry run textual --
  dev:tui:
    desc: runs text gallagher console in dev mode
    cmds:
      - poetry run textual run --dev gallagher.tui:main
  dev:py:
    desc: runs python in the poetry shell
    cmds: 
      - poetry run python -- {{.CLI_ARGS}}
  debug:get:
    desc: use httpie to get payload from CC
    summary: |
      runs a httpie get against the gallagher aus gateway
      appends the required headers, assumes the environment
      variables are set.

      you must pass in the partial url (past /api), 
      along with any parameters.

      by no suffix is provided CC returns a list of hateoas
      compliant endpoints.
    cmds:
      - |
        http get \
        https://commandcentre-api-au.security.gallagher.cloud/api/{{.CLI_ARGS}} \
        "Authorization: GGL-API-KEY $GACC_API_KEY"

