version: '3'

dotenv: ['.env']

tasks:
  build:image:
    desc: builds publishable python package
    cmds:
      - poetry build
  dev:test:
    desc: runs tests inside the server container
    cmds:
      - poetry run coverage run -m pytest -s
  dev:coverreport:
    desc: runs coverage inside the server container
    cmds:
      - poetry run coverage report -m
