site_name: Gallagher Python Toolkit
site_url: https://anomaly.github.io/gallagher/
repo_url: https://github.com/anomaly/gallagher/
site_author: Dev Mukherjee

theme:
  name: material

markdown_extensions:
    - mkdocs-typer
    - codehilite
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

nav:
  - Introduction: index.md
  - Installation & Usage: installation.md
  - SQL and SQLAlchemy: sql.md
  - Command Line Interface: cli.md
  - Terminal User Interface: tui.md 
  - Python SDK: python-sdk.md
  - Contributor's Manual: design.md
